# Jupyter Book Configuration
#######################################################################################
# Book settings
title: The Great Jupyter-Book
author: An author name

#######################################################################################
# Execution settings
execute:
  execute_notebooks: force

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true
  use_issues_button: true
  use_multitoc_numbering: true
  home_page_in_navbar: true

#######################################################################################
# Repository specification settings
repository:
  url: https://github.com/d33bs/demo-jupyter-book-web-accessibility-issues
  path_to_book: "src/book"
  branch: main
